- name: Install aptitude using apt
  apt: 
    name: aptitude 
    state: latest 
    update_cache: yes

- name: Install required system packages
  apt: 
    name: '{{ item }}'
    state: latest
    update_cache: yes
  loop: '{{ system_apps }}'