- name: Add VSCode GPG apt Key
  apt_key:
    url: '{{ vscode_key }}'
    state: present

- name: Add VSCode Repository
  apt_repository:
    repo: '{{ vscode_repo }}'
    state: present

- name: Update apt and install VSCode
  apt: 
    update_cache: yes
    name: code
    state: latest